### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "9b9b51b8d09346ea8b6026ef4576aadc",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/f8e3579a22d24962be9008dd39401aa7
