### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "3e0f924d06724b52b4a8eaf80d50735b",
  "accountNumber": "1000000002",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/f8e3579a22d24962be9008dd39401aa7
